name: ci

on:
  # only trigger on push and PR to master branch
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Installing Node
        uses: actions/setup-node@v1
        with:
          version: 12
      - run: |
          npm install
